addons: {chrome: stable}
dart: [stable]
dist: trusty
language: dart
notifications: {email: false}
sudo: required

install: pub get
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: pub run grinder test
