name: Continuous integration
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Check environment
        run: |
          dart --version
          pub --version
      - name: Fetch sources
        uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run grinder test
